-- MySQL Script generated by MySQL Workbench
-- Sat Feb 17 22:37:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ShenlongComics
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ShenlongComics
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ShenlongComics` DEFAULT CHARACTER SET utf8 ;
USE `ShenlongComics` ;

-- -----------------------------------------------------
-- Table `ShenlongComics`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShenlongComics`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShenlongComics`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShenlongComics`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `FechaNac` DATE NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `pasword` VARCHAR(45) NOT NULL,
  `id_rol` INT NOT NULL,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `id_rol_UNIQUE` (`id_rol` ASC),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC),
  INDEX `fk_usuarios_roles1_idx` (`roles_id` ASC),
  CONSTRAINT `fk_usuarios_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `ShenlongComics`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShenlongComics`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShenlongComics`.`categorias` (
  `idCategorias` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShenlongComics`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShenlongComics`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombreProd` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `precio` DECIMAL NOT NULL,
  `descuento` DECIMAL NULL,
  `stock` INT NULL,
  `categorias_idCategorias` INT NOT NULL,
  PRIMARY KEY (`id`, `categorias_idCategorias`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_productos_categorias_idx` (`categorias_idCategorias` ASC),
  CONSTRAINT `fk_productos_categorias`
    FOREIGN KEY (`categorias_idCategorias`)
    REFERENCES `ShenlongComics`.`categorias` (`idCategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ShenlongComics`.`carritoDeCompras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShenlongComics`.`carritoDeCompras` (
  `usuarios_id` INT NOT NULL,
  `productos_id` INT NOT NULL,
  `productos_categorias_idCategorias` INT NOT NULL,
  `id_carrito` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL,
  PRIMARY KEY (`id_carrito`),
  INDEX `fk_usuarios_has_productos_productos1_idx` (`productos_id` ASC, `productos_categorias_idCategorias` ASC),
  INDEX `fk_usuarios_has_productos_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_usuarios_has_productos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `ShenlongComics`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_productos_productos1`
    FOREIGN KEY (`productos_id`, `productos_categorias_idCategorias`)
    REFERENCES `ShenlongComics`.`productos` (`id`, `categorias_idCategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;
